[spyder_snippet]
    prefix = 'snippet'
    language = 'toml'
    content = '''
[${1:name}]
    prefix = '${1:prefix}'
    language = '${1:python}'
    # if you are going to use multiline use single triple quotes
    # double quotes trim all white space.
    body = '${1:import antigravity}'
'''
